# Generated by Django 6.0.3 on 2026-03-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creado_en',
            new_name='fecha_publicacion',
        ),
    ]
